/* 
 * This file is part of rootie.
 *
 * rootie is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * rootie is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with rootie.  If not, see <http://www.gnu.org/licenses/>.
 */

// Coloring for special files like README, CHANGELOG and others
export const specialFiles = [
    'README',
    'README.md',
    'readme',
    'readme.md',
    'CHANGELOG',
    'CHANGELOG.md',
    'changelog',
    'changelog.md',
    'LICENSE',
    'LICENSE.md',
    'license',
    'license.md',
    'CMakeLists.txt',
    ".bashrc",
    ".bash_profile",
    ".profile",
    ".zshrc",
    ".zprofile",
    ".zlogin",
    ".zlogout",
    ".zshenv",
    ".cshrc",
    ".tcshrc",
    ".kshrc",
    ".login",
    ".logout",
    ".inputrc",
    ".vimrc",
    ".gvimrc",
    ".emacs",
    ".nanorc",
    ".screenrc",
    ".tmux.conf",
    ".gitconfig",
    ".gitignore",
    ".gitattributes",
    ".hgignore",
    ".hgrc",
    ".npmrc",
    ".yarnrc",
    ".eslintrc",
    ".eslintrc.json",
    ".eslintrc.yaml",
    ".eslintrc.yml",
    ".eslintrc.js",
    ".prettierrc",
    ".prettierrc.json",
    ".prettierrc.yaml",
    ".prettierrc.yml",
    ".prettierrc.js",
    ".prettierignore",
    ".stylelintrc",
    ".stylelintrc.json",
    ".stylelintrc.yaml",
    ".stylelintrc.yml",
    ".stylelintrc.js",
    ".stylelintignore",
    ".eslintignore",
    ".babelrc",
    ".babelrc.json",
    ".babelrc.js",
    ".babelignore",
    ".dockerignore",
    ".gcloudignore",
    ".terraformrc",
    ".terragrunt.hcl",
    ".ansible.cfg",
    ".pylintrc",
    ".flake8",
    ".mypy.ini",
    ".pep8",
    ".editorconfig",
    ".aws/config",
    ".aws/credentials",
    ".vscode/settings.json",
    ".vscode/extensions.json",
    "package.json",
    "package-lock.json",
    "tsconfig.json",
    "jsconfig.json",
    "composer.json",
    "webpack.config.js",
    "rollup.config.js",
    "gruntfile.js",
    "gulpfile.js",
    "jest.config.js",
    "karma.conf.js",
    "protractor.conf.js",
    "postcss.config.js",
    "tailwind.config.js",
    "babel.config.js",
    "nuxt.config.js",
    "next.config.js",
    "gatsby-config.js",
    "vue.config.js",
    "angular.json",
    "svelte.config.js",
    "capacitor.config.json",
    "ionic.config.json",
    "snowpack.config.js",
    "metro.config.js",
    ".env",
    ".env.local",
    ".env.development",
    ".env.test",
    ".env.production"
]